[34m[1mwandb[39m[22m: [32m[41mERROR[39m[49m Project banusacli/. does not contain artifact: "output"
Traceback (most recent call last):
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/wandb/apis/public.py", line 958, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/wandb/apis/public.py", line 4356, in __init__
    self._load()
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/wandb/apis/public.py", line 5077, in _load
    raise ValueError(
ValueError: Project banusacli/. does not contain artifact: "output"
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/banubilmez/Courses/MLOps/MLOps-zoomcamp-2023/homework_2/wandb/train.py", line 66, in <module>
    run_train()
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/banubilmez/Courses/MLOps/MLOps-zoomcamp-2023/homework_2/wandb/train.py", line 41, in run_train
    artifact = wandb.use_artifact(data_artifact, type="preprocessed_dataset")
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 345, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 335, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2676, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/wandb/apis/public.py", line 958, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/wandb/apis/public.py", line 4356, in __init__
    self._load()
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/wandb/apis/public.py", line 5077, in _load
    raise ValueError(
wandb.errors.CommError: Project banusacli/. does not contain artifact: "output"