Traceback (most recent call last):
  File "/Users/banubilmez/Courses/MLOps/MLOps-zoomcamp-2023/homework_2/wandb/train.py", line 66, in <module>
    run_train()
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/banubilmez/Courses/MLOps/MLOps-zoomcamp-2023/homework_2/wandb/train.py", line 41, in run_train
    artifact = wandb.use_artifact(data_artifact, type="preprocessed_dataset")
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 345, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 335, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/banubilmez/.pyenv/versions/3.10.4/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2734, in use_artifact
    raise ValueError(
ValueError: You must pass an artifact name (e.g. "pedestrian-dataset:v1"), an instance of `wandb.Artifact`, or `wandb.Api().artifact()` to `use_artifact`